site_name: KISK Portfolio - Pavel Dytrych
docs_dir: md
site_dir: docs
nav:
  - KISK?: about.md
  - Texty: index.md
  - O mě: contact.md

theme:
  name: mkdocs
  locale: cs
  color_mode: light
  nav_style: light